# Generated by Django 6.1.1 on 2026-09-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deduct_from_finance',
            field=models.BooleanField(default=False, help_text='When checked, the total cost (unit_price × quantity_total) is recorded as a withdrawal in the Finance module.', verbose_name='Deduct cost from Finance (creates a Withdrawal)'),
        ),
    ]
